# This file was generated by GoReleaser. DO NOT EDIT.
cask "pkms" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "92758463305a1a81c812c9c979598b3034da7bf84c47dca8ae9429c99b8acadc"
      url "https://github.com/rdegges/pkms/releases/download/v#{version}/pkms_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "21961cd102d654d360046521345918d34612d30e045311b4a4455fe450ddc501"
      url "https://github.com/rdegges/pkms/releases/download/v#{version}/pkms_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c3602127cb6e6d01e9ed41d78f0d9a2a5142c6539bdc6e16c70ca547c96d8659"
      url "https://github.com/rdegges/pkms/releases/download/v#{version}/pkms_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a61916e24c1d8e6fcf17aa43753f59c79c7109ea622ca51b8f8710f765fd3a83"
      url "https://github.com/rdegges/pkms/releases/download/v#{version}/pkms_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "pkms"
  desc "Deterministic manager for Obsidian-compatible markdown vaults: scaffold, lint, snapshot, query"
  homepage "https://github.com/rdegges/pkms"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pkms"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pkms"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Snapshots use git (>= 2.30). Everything else works without it.
    Get started: pkms init --path ~/Vault
  EOS
end
