# This file was generated by GoReleaser. DO NOT EDIT.
cask "pkms" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "e738dc4dcbe057784dd0089013c3fc6e8e54a8df8119bdc0e2a7a3f687757164"
      url "https://github.com/rdegges/pkms/releases/download/v#{version}/pkms_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0203ad5c7d7b916396eed26d817cd2e979f061d4437523600351ffdefd20ee87"
      url "https://github.com/rdegges/pkms/releases/download/v#{version}/pkms_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "988bf05e62b21e246bb2671c1cfd2fc968551d9eb09e724077fca99fecc6fbfe"
      url "https://github.com/rdegges/pkms/releases/download/v#{version}/pkms_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "40d02053098478038dbeab63952d4e42546da818c89bf9ea57cc0fc440428daf"
      url "https://github.com/rdegges/pkms/releases/download/v#{version}/pkms_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "pkms"
  desc "Deterministic manager for Obsidian-compatible markdown vaults: scaffold, lint, snapshot, query"
  homepage "https://github.com/rdegges/pkms"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pkms"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pkms"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Snapshots use git (>= 2.30). Everything else works without it.
    Get started: pkms init --path ~/Vault
  EOS
end
