# This file was generated by GoReleaser. DO NOT EDIT.
cask "pkms" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "5dd327ebfd7cdeccde1970784f15d446441af0bc55c6b8f50551ca677213ec0e"
      url "https://github.com/rdegges/pkms/releases/download/v#{version}/pkms_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "402bfb35ac6c0987eb4d24df088a15b98c9b48c66c2fda84a009d70e048a1fae"
      url "https://github.com/rdegges/pkms/releases/download/v#{version}/pkms_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "614f03c1c12a511a8bd15f0916e908bcccb668a9747112bd2f8973ecfe2264c8"
      url "https://github.com/rdegges/pkms/releases/download/v#{version}/pkms_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3ed976cd5e4d2ac7b82ae6e9f3d9963734638ad7a982b200bb904900b7ce110b"
      url "https://github.com/rdegges/pkms/releases/download/v#{version}/pkms_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "pkms"
  desc "Deterministic manager for Obsidian-compatible markdown vaults: scaffold, lint, snapshot, query"
  homepage "https://github.com/rdegges/pkms"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pkms"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pkms"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Snapshots use git (>= 2.30). Everything else works without it.
    Get started: pkms init --path ~/Vault
  EOS
end
