# This file was generated by GoReleaser. DO NOT EDIT.
cask "powermon" do
  name "powermon"
  desc "Cross-platform power consumption monitor with interactive terminal UI"
  homepage "https://github.com/rdegges/powermon"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "powermon"

  on_macos do
    on_intel do
      url "https://github.com/rdegges/powermon/releases/download/v#{version}/powermon_#{version}_darwin_amd64.tar.gz"
      sha256 "fe6025b236863263cf91858ed9928acd3a7fa1e48376b8a9a153c9a5fa7d3df4"
    end
    on_arm do
      url "https://github.com/rdegges/powermon/releases/download/v#{version}/powermon_#{version}_darwin_arm64.tar.gz"
      sha256 "980b830e8a2d9c54ea8c88a38d9932c75a99f3b717eca02dd58a175c786a935a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rdegges/powermon/releases/download/v#{version}/powermon_#{version}_linux_amd64.tar.gz"
      sha256 "ec0884212ddd69ebeb54e0fa4f733143bd7b300f4463efcf7a8520d44f45e285"
    end
    on_arm do
      url "https://github.com/rdegges/powermon/releases/download/v#{version}/powermon_#{version}_linux_arm64.tar.gz"
      sha256 "558976c8f3156f899efe1913582a714b514f21591f35660b9f25c4c6e7d3ed3c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/powermon"]
    end
  end

  caveats do
    "To run powermon on desktop Macs (Mac mini, iMac, Mac Studio, Mac Pro),"
    "use sudo for power monitoring: sudo powermon"
  end

  # No zap stanza required
end
