# This file was generated by GoReleaser. DO NOT EDIT.
cask "powermon" do
  name "powermon"
  desc "Cross-platform power consumption monitor with interactive terminal UI"
  homepage "https://github.com/rdegges/powermon"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "powermon"

  on_macos do
    on_intel do
      url "https://github.com/rdegges/powermon/releases/download/v#{version}/powermon_#{version}_darwin_amd64.tar.gz"
      sha256 "99747e7bfc92f3b995cf1fc00a75885107c661c7349dd89127a5f439e322d185"
    end
    on_arm do
      url "https://github.com/rdegges/powermon/releases/download/v#{version}/powermon_#{version}_darwin_arm64.tar.gz"
      sha256 "c35f73203d3839a3342b60cc74cc16f1997a481801107463fdf016264a9bf383"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rdegges/powermon/releases/download/v#{version}/powermon_#{version}_linux_amd64.tar.gz"
      sha256 "9a996cdadbb0fd5b93bba278ced4bf71ea4b17bfe5645c526b33712d5fa0931d"
    end
    on_arm do
      url "https://github.com/rdegges/powermon/releases/download/v#{version}/powermon_#{version}_linux_arm64.tar.gz"
      sha256 "42b758d8131a00e01bb5634722544aa5f8a0a3c4402e205b63bd8fe06a5abdeb"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/powermon"]
    end
  end

  caveats do
    "To run powermon on desktop Macs (Mac mini, iMac, Mac Studio, Mac Pro),"
    "use sudo for power monitoring: sudo powermon"
  end

  # No zap stanza required
end
