# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Redline < Formula
  desc "Audit your website content against canonical messaging + GEO target prompts. Emits an agent-actionable edit plan."
  homepage "https://github.com/rdegges/redline"
  version "0.1.0-alpha"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rdegges/redline/releases/download/v0.1.0-alpha/redline_0.1.0-alpha_Darwin_x86_64.tar.gz"
      sha256 "411607e13e48c49b967235341b4ddcfde76fc8c45e5961d8d96f0f8286906d2a"

      define_method(:install) do
        bin.install "redline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rdegges/redline/releases/download/v0.1.0-alpha/redline_0.1.0-alpha_Darwin_arm64.tar.gz"
      sha256 "969033b4fa8993feb0eb51765cd29fb0f3c442610465506e350766b066284eb2"

      define_method(:install) do
        bin.install "redline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rdegges/redline/releases/download/v0.1.0-alpha/redline_0.1.0-alpha_Linux_x86_64.tar.gz"
      sha256 "62040cdc06a63d4100e6d35baf4210269ede1dc753e3ec617cd21fdd83973b8a"
      define_method(:install) do
        bin.install "redline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rdegges/redline/releases/download/v0.1.0-alpha/redline_0.1.0-alpha_Linux_arm64.tar.gz"
      sha256 "32228eda46c5c05bc233fbfe32446f4a9b921f0f4485466b5c8dcfc49819baa6"
      define_method(:install) do
        bin.install "redline"
      end
    end
  end

  test do
    system "#{bin}/redline", "version"
  end
end
